force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ON-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Order</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/DeliveryType__c.field-meta.xml
<CustomField>
    <fullName>DeliveryType__c</fullName>
    <label>Delivery Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderBuilder.cls
/*
* @author Gustavo Lincoln
*/
public virtual class OrderBuilder {

    public Order__c buildOrder( Account account, OrderController.OrderDeliveryAddress address ) {

        return new Order__c(Account__c = account.Id, 
                            OwnerId = UserInfo.getUserId(), 
                            Status__c = 'Activated', 
                            StartDate__c = System.today(),
                            Address__c = address.address,
                            DeliveryDate__c = address.deliveryDate,
                            DeliveryType__c = address.delivery);

    }

}