force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ON-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{00000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrderItemService.cls
/*
* @author Gustavo Lincoln
*/
public virtual class OrderItemService {
    
    private OrderItemTransformer transformer;
    private OrderItemRepository repository;

    public OrderItemService() {
        transformer = new OrderItemTransformer();
        repository = new OrderItemRepository();
    }

    public List<OrderItem__c> createOrdersItems( Order__c order, List<OrderDetail> orderDetails ) {

        List<OrderItem__c> orderItems = new List<OrderItem__c>();

        for( OrderDetail orderDetail : orderDetails ) {

            orderItems.add( buildOrderItem( order, orderDetail ) );

        }

        if( orderItems.isEmpty() ) return new List<OrderItem__c>();

        return repository.save( orderItems );

    }
    
    public OrderItem__c buildOrderItem( Order__c order, OrderDetail orderDetail ) {

        return transformer.toOrderItem( order, orderDetail );

    }


}