force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ON-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{00000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrderService.cls
/*
* @author Gustavo Lincoln
*/
public virtual class OrderService {
    
    private OrderBuilder builder;
    private OrderRepository repository;
    private AccountService accountService;
    private OrderItemService orderItemService;

    public OrderService() {
        builder = new OrderBuilder();
        repository = new OrderRepository();
        accountService = new AccountService();
        orderItemService = new orderItemService();
    }

    public Order__c processOrders( List<OrderDetail> orderDetails, OrderController.OrderDeliveryAddress address ) {

        //create an account to associate with current user
        Account account = accountService.createAccount();

        //create
        Order__c order = (Order__c) repository.save( builder.buildOrder( account, address ) );

        //create OrderItems
        List<OrderItem__c> orderItems = orderItemService.createOrdersItems( order, orderDetails );

        return order;

    }

}