force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Ordem</label>
    <nameField>
        <displayFormat>ON-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>Total Price</label>
    <summarizedField>OrderItem__c.Price__c</summarizedField>
    <summaryForeignKey>OrderItem__c.Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/OrderSummaryController.cls
/*
* @author Gustavo Lincoln
*/
public with sharing class OrderSummaryController {
    
    @AuraEnabled
    public static List<Purchase> findPurchases( String userId ) {

        List<Order__c> orders = [ SELECT Id, Name, TotalPrice__c, Status__c, Address__c FROM Order__c WHERE OwnerId =: userId ];

        List<Purchase> purchases = new List<Purchase>();

        for( Order__c order : orders ) {

            purchases.add( new Purchase( order.Id, order.Name, order.Address__c, order.TotalPrice__c, order.Status__c ) );

        }

        return purchases;
    }

    @AuraEnabled
    public static List<Purchase> removePurchase( String userId, String orderId ) {

        Order__c order = new OrderRepository().findById( orderId );
        
        if( order != null ) delete order;

        return findPurchases( userId );
    
    }



    public class Purchase {

        @AuraEnabled
        public String id { get; set; }

        @AuraEnabled
        public String name { get; set; }

        @AuraEnabled
        public String address { get; set; }
        
        @AuraEnabled
        public Decimal totalPrice { get; set; }

        @AuraEnabled
        public String status { get; set; }

        public Purchase( String id, String name,String address, Decimal totalPrice, String status ) {
            this.id = id;
            this.name = name;
            this.address = address;
            this.totalPrice = totalPrice;
            this.status = status;
        }
        
    }

}